"""
Tests for app/architecture/inventory.py — the bounded repository walk.
All tests are fully offline and use tmp_path trees (no committed fixtures).
"""

from pathlib import Path

from app.architecture import inventory as inv_mod


def _write(root: Path, rel: str, content: str = "") -> Path:
    p = root / rel
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    return p


# ── skip rules ────────────────────────────────────────────────────────────────


def test_node_modules_and_extra_skip_dirs_are_pruned(tmp_path):
    _write(tmp_path, "node_modules/pkg/index.js", "module.exports = {}")
    _write(tmp_path, "target/debug/x.rs", "fn main() {}")
    _write(tmp_path, "app/main.py", "x = 1\n")
    inv = inv_mod.build_inventory(tmp_path)
    paths = {f.rel_path for f in inv.files}
    assert paths == {"app/main.py"}


def test_binary_file_is_skipped_but_counted_as_discovered(tmp_path):
    (tmp_path / "blob.py").write_bytes(b"\x00\x01\x02binary")
    inv = inv_mod.build_inventory(tmp_path)
    assert inv.files_discovered == 1
    assert inv.files == []
    assert inv.skipped_reasons.get("binary") == 1


def test_lockfile_suffix_is_skipped(tmp_path):
    _write(tmp_path, "poetry.lock", "irrelevant")
    inv = inv_mod.build_inventory(tmp_path)
    assert inv.files == []
    assert inv.skipped_reasons.get("binary_or_lockfile") == 1


# ── secret guard ──────────────────────────────────────────────────────────────


def test_env_file_is_never_opened(tmp_path, monkeypatch):
    _write(tmp_path, ".env", "SECRET_KEY=hunter2-abcdefghijklmnop\n")

    real_open = open

    def guarded_open(path, *a, **kw):
        if str(path).endswith(".env") and "example" not in str(path):
            raise AssertionError(f".env was opened: {path}")
        return real_open(path, *a, **kw)

    monkeypatch.setattr("builtins.open", guarded_open)
    inv = inv_mod.build_inventory(tmp_path)
    assert inv.files == []
    assert inv.skipped_reasons.get("secret_guarded") == 1


def test_env_example_survives_and_is_config_doc(tmp_path):
    _write(tmp_path, ".env.example", "DATABASE_URL=\nSECRET=\n")
    inv = inv_mod.build_inventory(tmp_path)
    assert len(inv.files) == 1
    assert inv.files[0].is_config_doc is True


def test_pem_and_key_files_are_secret_guarded(tmp_path):
    _write(tmp_path, "certs/server.pem", "-----BEGIN CERTIFICATE-----")
    _write(tmp_path, "certs/server.key", "-----BEGIN PRIVATE KEY-----")
    inv = inv_mod.build_inventory(tmp_path)
    assert inv.files == []
    assert inv.skipped_reasons.get("secret_guarded") == 2


# ── generated-file detection ──────────────────────────────────────────────────


def test_generated_protobuf_is_skipped(tmp_path):
    _write(tmp_path, "app_pb2.py", "# generated\n")
    inv = inv_mod.build_inventory(tmp_path)
    assert inv.files == []
    assert inv.skipped_reasons.get("generated") == 1


def test_generated_header_marker_is_skipped(tmp_path):
    _write(tmp_path, "wire.py", "# Code generated by protoc-gen. DO NOT EDIT.\nx = 1\n")
    inv = inv_mod.build_inventory(tmp_path)
    assert inv.files == []
    assert inv.skipped_reasons.get("generated") == 1


def test_short_file_does_not_crash_generated_header_check(tmp_path):
    """Regression: next() inside a generator expression raised StopIteration
    (PEP 479 -> RuntimeError) for files with fewer than 3 lines."""
    _write(tmp_path, "empty.py", "")
    _write(tmp_path, "one_line.py", "x = 1")
    inv = inv_mod.build_inventory(tmp_path)
    assert {f.rel_path for f in inv.files} == {"empty.py", "one_line.py"}


# ── special extension-less filenames ──────────────────────────────────────────


def test_dockerfile_survives_despite_no_extension(tmp_path):
    _write(tmp_path, "Dockerfile", "FROM python:3.12-slim\n")
    _write(tmp_path, "docker/Dockerfile.prod", "FROM python:3.12-slim\n")
    inv = inv_mod.build_inventory(tmp_path)
    paths = {f.rel_path for f in inv.files}
    assert "Dockerfile" in paths
    assert "docker/Dockerfile.prod" in paths
    assert all(f.is_config_doc for f in inv.files)


# ── oversize files ────────────────────────────────────────────────────────────


def test_oversize_file_is_excluded_but_counted(tmp_path, monkeypatch):
    monkeypatch.setattr(inv_mod, "ARCH_MAX_FILE_BYTES", 10)
    _write(tmp_path, "big.py", "x" * 100)
    inv = inv_mod.build_inventory(tmp_path)
    assert inv.files == []
    assert inv.source_files_discovered == 1  # still counted for language stats
    assert inv.skipped_reasons.get("oversize_file") == 1


# ── walk truncation ───────────────────────────────────────────────────────────


def test_walk_truncates_at_max_discovered_files(tmp_path, monkeypatch):
    monkeypatch.setattr(inv_mod, "ARCH_MAX_DISCOVERED_FILES", 3)
    for i in range(10):
        _write(tmp_path, f"file_{i}.py", "x = 1\n")
    inv = inv_mod.build_inventory(tmp_path)
    assert inv.truncated_walk is True
    assert inv.files_discovered >= 3


def test_symlink_is_not_followed(tmp_path):
    real_dir = tmp_path / "real"
    real_dir.mkdir()
    _write(tmp_path, "real/a.py", "x = 1\n")
    link = tmp_path / "linked"
    try:
        link.symlink_to(real_dir, target_is_directory=True)
    except OSError:
        return  # symlinks unavailable/unprivileged on this platform — nothing to assert
    inv = inv_mod.build_inventory(tmp_path)
    paths = {f.rel_path for f in inv.files}
    assert paths == {"real/a.py"}  # not duplicated via the symlink


# ── choose_tier ───────────────────────────────────────────────────────────────


def test_choose_tier_1_when_within_budget(tmp_path):
    _write(tmp_path, "app/main.py", "x = 1\n")
    inv = inv_mod.build_inventory(tmp_path)
    tier, reason = inv_mod.choose_tier(inv)
    assert (tier, reason) == (1, None)


def test_choose_tier_2_when_parsed_files_budget_exceeded(tmp_path, monkeypatch):
    monkeypatch.setattr(inv_mod, "ARCH_MAX_PARSED_FILES", 1)
    _write(tmp_path, "a.py", "x = 1\n")
    _write(tmp_path, "b.py", "x = 1\n")
    inv = inv_mod.build_inventory(tmp_path)
    tier, reason = inv_mod.choose_tier(inv)
    assert (tier, reason) == (2, "ARCH_MAX_PARSED_FILES")


def test_choose_tier_3_when_walk_truncated(tmp_path, monkeypatch):
    monkeypatch.setattr(inv_mod, "ARCH_MAX_DISCOVERED_FILES", 1)
    _write(tmp_path, "a.py", "x = 1\n")
    _write(tmp_path, "b.py", "x = 1\n")
    inv = inv_mod.build_inventory(tmp_path)
    tier, reason = inv_mod.choose_tier(inv)
    assert (tier, reason) == (3, "ARCH_MAX_DISCOVERED_FILES")


def test_choose_tier_3_when_no_source_files_at_all(tmp_path):
    (tmp_path / "notes.pdf").write_bytes(b"%PDF-1.4")  # binary suffix, skipped entirely
    inv = inv_mod.build_inventory(tmp_path)
    tier, reason = inv_mod.choose_tier(inv)
    assert (tier, reason) == (3, "no_source_files_found")


def test_choose_tier_2_when_only_unsupported_languages(tmp_path):
    _write(tmp_path, "Main.java", "class Main {}\n")
    inv = inv_mod.build_inventory(tmp_path)
    tier, reason = inv_mod.choose_tier(inv)
    assert (tier, reason) == (2, "no_supported_source_files")
    assert inv.languages == {"Java": 1}


# ── priority_key ──────────────────────────────────────────────────────────────


def test_priority_key_prefers_shallower_files(tmp_path):
    shallow = _write(tmp_path, "top.py", "x = 1\n")
    deep = _write(tmp_path, "a/b/c/deep.py", "x = 1\n")
    inv = inv_mod.build_inventory(tmp_path)
    ordered = sorted(inv.files, key=inv_mod.priority_key)
    assert ordered[0].abs_path == shallow
    assert ordered[-1].abs_path == deep
