"""
Loader for the curated OptiLearn architecture artifact.

The artifact (curated/optilearn/architecture.json + detail.mmd + manifest.json)
is authored and versioned by hand — see curated/optilearn/README.md — not
generated by this pipeline. It is validated at load time so an accidental
deletion, truncation, or edit that breaks a guarantee (evidence paths,
component/relationship counts, content hash) fails loudly instead of silently
drifting from what ships. Loading touches no network, no Granite, no Bob, and
no Docker: it works with every external model service unavailable.
"""

import hashlib
import json
import time
import uuid
from functools import lru_cache
from pathlib import Path

from app.architecture import mermaid as mermaidmod
from app.config import OPTILEARN_SRC
from app.models.contracts import (
    ArchitectureComponent,
    ArchitectureRelationship,
    ArchitectureReport,
    DataStore,
    DeploymentArtifact,
    Entrypoint,
    ExternalService,
    TechnologyStack,
)
from app.pipelines.context import safe_path

_DIR = Path(__file__).parent / "curated" / "optilearn"


class CuratedArtifactError(RuntimeError):
    """The curated artifact is missing, corrupt, or fails validation."""


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


@lru_cache(maxsize=1)
def _load() -> ArchitectureReport:
    arch_path = _DIR / "architecture.json"
    detail_path = _DIR / "detail.mmd"
    manifest_path = _DIR / "manifest.json"

    try:
        manifest = json.loads(manifest_path.read_text("utf-8"))
        arch_raw = json.loads(arch_path.read_text("utf-8"))
        detail_mmd = detail_path.read_text("utf-8")
    except OSError as exc:
        raise CuratedArtifactError(
            f"curated OptiLearn artifact is missing a required file: {exc}"
        ) from exc
    except json.JSONDecodeError as exc:
        raise CuratedArtifactError(
            f"curated OptiLearn artifact contains invalid JSON: {exc}"
        ) from exc

    expected_hashes = manifest.get("sha256", {})
    for fname, path in (("architecture.json", arch_path), ("detail.mmd", detail_path)):
        expected = expected_hashes.get(fname)
        if expected and _sha256(path) != expected:
            raise CuratedArtifactError(
                f"curated OptiLearn artifact is corrupted: {fname} does not match its recorded hash"
            )

    try:
        components = [ArchitectureComponent(**c) for c in arch_raw["components"]]
        relationships = [
            ArchitectureRelationship(**r) for r in arch_raw["relationships"]
        ]
        entrypoints = [Entrypoint(**e) for e in arch_raw.get("entrypoints", [])]
        external_services = [
            ExternalService(**e) for e in arch_raw.get("external_services", [])
        ]
        data_stores = [DataStore(**d) for d in arch_raw.get("data_stores", [])]
        deployment = [DeploymentArtifact(**d) for d in arch_raw.get("deployment", [])]
        stack = TechnologyStack(**arch_raw["technology_stack"])
    except (KeyError, TypeError, ValueError) as exc:
        raise CuratedArtifactError(
            f"curated OptiLearn artifact does not match the expected shape: {exc}"
        ) from exc

    expected_components = manifest.get("expected_components")
    if expected_components is not None and len(components) != expected_components:
        raise CuratedArtifactError(
            f"curated OptiLearn artifact has {len(components)} components, "
            f"expected {expected_components}"
        )
    expected_relationships = manifest.get("expected_relationships")
    if (
        expected_relationships is not None
        and len(relationships) != expected_relationships
    ):
        raise CuratedArtifactError(
            f"curated OptiLearn artifact has {len(relationships)} relationships, "
            f"expected {expected_relationships}"
        )

    for comp in components:
        for ev in comp.evidence:
            if ev.verified and safe_path(OPTILEARN_SRC, ev.path) is None:
                raise CuratedArtifactError(
                    f"curated OptiLearn artifact references a missing bundled file "
                    f"for component '{comp.id}': {ev.path}"
                )

    overview_mermaid = mermaidmod.generate_from_parts(components, relationships)
    problems = mermaidmod.validate(overview_mermaid)
    if problems:
        raise CuratedArtifactError(
            f"curated OptiLearn overview diagram failed validation: {problems}"
        )
    detail_problems = mermaidmod.validate(detail_mmd)
    if detail_problems:
        raise CuratedArtifactError(
            f"curated OptiLearn detail diagram failed validation: {detail_problems}"
        )

    return ArchitectureReport(
        architecture_id="__template__",
        scan_id="__template__",
        status="complete",
        source="curated",
        repo_source="demo",
        summary=arch_raw["summary"],
        technology_stack=stack,
        entrypoints=entrypoints,
        components=components,
        relationships=relationships,
        external_services=external_services,
        data_stores=data_stores,
        deployment=deployment,
        mermaid=overview_mermaid,
        detail_mermaid=detail_mmd,
        coverage=None,
        warnings=[],
        limitations=arch_raw.get("limitations", []),
        narrowing_suggestions=[],
        files_considered=[],
        files_parsed=[],
        files_skipped=[],
        curated_version=manifest["version"],
        generated_at=0.0,
    )


def load_curated(scan_id: str) -> ArchitectureReport:
    """A fresh copy of the curated template with a new architecture_id/scan_id/timestamp."""
    template = _load()
    report = template.model_copy(deep=True)
    report.architecture_id = str(uuid.uuid4())
    report.scan_id = scan_id
    report.generated_at = time.time()
    return report
