"""
Bounded repository inventory: walk the extracted tree, classify every file,
and decide which analysis tier applies. Read-only — never opens a value out
of a real .env file, never follows symlinks, never executes anything.

Reuses the skip-dir/skip-suffix/binary rules from app.ingest.limits (the same
rules the bug-scan file selector uses) and adds architecture-specific ones:
generated-file detection, a secret-filename guard, and a much larger file/byte
budget suited to structural coverage rather than per-line bug review.
"""

import os
import re
import time
from dataclasses import dataclass, field
from pathlib import Path

from app.config import (
    ARCH_MAX_DISCOVERED_FILES,
    ARCH_MAX_FILE_BYTES,
    ARCH_MAX_PARSED_FILES,
    ARCH_MAX_SOURCE_BYTES,
    ARCH_MAX_SOURCE_LINES,
)
from app.ingest.limits import SKIP_DIRS, SKIP_SUFFIXES, is_binary

# ── Language table ───────────────────────────────────────────────────────────
# Extension -> human-readable language name. Anything not in this table is
# either a config/doc file (see _CONFIG_DOC_EXTS) or reported as unknown.
LANGUAGE_BY_EXT: dict[str, str] = {
    ".py": "Python",
    ".pyi": "Python",
    ".js": "JavaScript",
    ".mjs": "JavaScript",
    ".cjs": "JavaScript",
    ".jsx": "JavaScript",
    ".ts": "TypeScript",
    ".mts": "TypeScript",
    ".tsx": "TypeScript",
    ".java": "Java",
    ".kt": "Kotlin",
    ".kts": "Kotlin",
    ".go": "Go",
    ".rs": "Rust",
    ".c": "C",
    ".h": "C",
    ".cpp": "C++",
    ".cc": "C++",
    ".hpp": "C++",
    ".cs": "C#",
    ".rb": "Ruby",
    ".php": "PHP",
    ".swift": "Swift",
    ".scala": "Scala",
    ".sh": "Shell",
    ".bash": "Shell",
    ".zsh": "Shell",
    ".sql": "SQL",
    ".dart": "Dart",
    ".vue": "Vue",
    ".svelte": "Svelte",
}

# Extractors exist for these languages today; everything else in
# LANGUAGE_BY_EXT is counted and reported, never silently skipped.
SUPPORTED_LANGUAGES: frozenset[str] = frozenset({"Python"})

# Well-known extension-less filenames that must survive the extension filter
# to reach manifests.py (Dockerfile has no suffix at all).
_SPECIAL_CONFIG_NAMES: frozenset[str] = frozenset(
    {
        "Dockerfile",
        "Makefile",
        "Procfile",
        "Jenkinsfile",
        "Vagrantfile",
        "Gemfile",
        "Rakefile",
    }
)


def _is_special_config_name(name: str) -> bool:
    if name in _SPECIAL_CONFIG_NAMES:
        return True
    return name.startswith("Dockerfile.")


_CONFIG_DOC_EXTS: frozenset[str] = frozenset(
    {
        ".yaml",
        ".yml",
        ".toml",
        ".json",
        ".xml",
        ".html",
        ".css",
        ".scss",
        ".md",
        ".txt",
        ".cfg",
        ".ini",
        ".conf",
    }
)

# Directories skipped in addition to app.ingest.limits.SKIP_DIRS — architecture
# analysis walks much deeper than the bug-scan file selector, so more build
# and cache output needs pruning.
_EXTRA_SKIP_DIRS: frozenset[str] = frozenset(
    {
        "target",
        ".gradle",
        ".terraform",
        "bin",
        "obj",
        "Pods",
        ".tox",
        "htmlcov",
        "site-packages",
        "bower_components",
        ".yarn",
        ".pnpm-store",
        "__snapshots__",
        ".cache",
        ".turbo",
        ".svelte-kit",
        "storybook-static",
    }
)

# Filenames/suffixes that are never opened, even to sniff a header — hard
# rule: no secret values in scan output, ever. `.env.example` and friends are
# handled separately (manifests.py opens them for key NAMES only).
_SECRET_SUFFIXES: frozenset[str] = frozenset(
    {".pem", ".key", ".p12", ".pfx", ".keystore", ".jks"}
)
_SECRET_NAMES: frozenset[str] = frozenset(
    {
        ".env",
        ".npmrc",
        ".netrc",
        "credentials",
        "id_rsa",
        "id_ed25519",
        "id_ecdsa",
        "id_dsa",
    }
)
ENV_EXAMPLE_NAMES: frozenset[str] = frozenset(
    {".env.example", ".env.sample", ".env.template", "env.example"}
)


def is_secret_file(name: str) -> bool:
    """True for a file that must never be opened, even for a name/line count."""
    if name in ENV_EXAMPLE_NAMES:
        return False
    if name in _SECRET_NAMES or name.startswith(".env."):
        return True
    suffix = Path(name).suffix.lower()
    return suffix in _SECRET_SUFFIXES or name.startswith("id_rsa")


_GENERATED_SUFFIXES: frozenset[str] = frozenset({".pb.go", ".g.dart", ".d.ts"})
_GENERATED_NAME_MARKERS: tuple[str, ...] = ("_pb2.py", "_pb2_grpc.py", ".generated.")
_GENERATED_HEADER_RE = re.compile(
    r"@generated|DO NOT EDIT|Code generated by", re.IGNORECASE
)


def _is_generated_name(name: str) -> bool:
    lower = name.lower()
    if any(lower.endswith(s) for s in _GENERATED_SUFFIXES):
        return True
    return any(marker in name for marker in _GENERATED_NAME_MARKERS)


def _looks_generated_header(path: Path) -> bool:
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            lines = [line for _, line in zip(range(3), fh, strict=False)]
    except OSError:
        return False
    return bool(_GENERATED_HEADER_RE.search("".join(lines)))


_MAX_LINE_LENGTH = 500


def _is_minified(path: Path) -> bool:
    """Same heuristic as app.ingest.limits._is_minified, kept local and small
    rather than importing a second module-private helper."""
    name = path.name.lower()
    if name.endswith((".min.js", ".min.css")):
        return True
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            for i, line in enumerate(fh):
                if i >= 5:
                    break
                if len(line) > _MAX_LINE_LENGTH:
                    return True
    except OSError:
        pass
    return False


def _count_lines_and_bytes(path: Path) -> tuple[int, int]:
    try:
        size = path.stat().st_size
        with open(path, encoding="utf-8", errors="replace") as fh:
            lines = sum(1 for _ in fh)
        return lines, size
    except OSError:
        return 0, 0


@dataclass
class FileRecord:
    rel_path: str  # posix, relative to root
    abs_path: Path
    ext: str
    size: int
    lines: int
    language: str | None  # None when the extension is unrecognised
    is_config_doc: bool
    is_test: bool
    is_generated: bool


@dataclass
class Inventory:
    root: Path
    files: list[FileRecord] = field(
        default_factory=list
    )  # eligible for parsing/manifest reading
    files_discovered: int = 0  # all files under non-skip dirs, before content filters
    source_files_discovered: int = 0  # recognised-language files among those
    languages: dict[str, int] = field(default_factory=dict)  # language -> file count
    source_bytes: int = 0
    source_lines: int = 0
    env_var_names: list[str] = field(default_factory=list)
    skipped_reasons: dict[str, int] = field(default_factory=dict)
    truncated_walk: bool = False

    def _bump(self, reason: str) -> None:
        self.skipped_reasons[reason] = self.skipped_reasons.get(reason, 0) + 1

    @property
    def source_files_supported(self) -> int:
        return sum(1 for f in self.files if f.language in SUPPORTED_LANGUAGES)


_TEST_PATH_RE = re.compile(
    r"(^|/)(tests?|__tests__|spec)(/|$)|[_.-]test\.|[_.-]spec\.|^test_|_test\.py$"
)


def _is_test_path(rel_posix: str) -> bool:
    return bool(_TEST_PATH_RE.search(rel_posix.lower()))


def build_inventory(root: Path, deadline_monotonic: float | None = None) -> Inventory:
    """
    Walk *root* and classify every file. Synchronous and CPU/disk-bound —
    callers run this via asyncio.to_thread.

    *deadline_monotonic*, if given, is a time.monotonic() cutoff; the walk
    stops (marking truncated_walk) if it runs past it, in addition to the
    ARCH_MAX_DISCOVERED_FILES hard cap.
    """
    inv = Inventory(root=root)
    skip_dirs = SKIP_DIRS | _EXTRA_SKIP_DIRS

    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        dirnames[:] = [
            d
            for d in dirnames
            if d not in skip_dirs and not (d.startswith(".") and d != ".github")
        ]

        if inv.files_discovered >= ARCH_MAX_DISCOVERED_FILES:
            inv.truncated_walk = True
            break
        if deadline_monotonic is not None and time.monotonic() > deadline_monotonic:
            inv.truncated_walk = True
            break

        for fname in filenames:
            if inv.files_discovered >= ARCH_MAX_DISCOVERED_FILES:
                inv.truncated_walk = True
                break

            fpath = Path(dirpath) / fname
            try:
                if fpath.is_symlink() or not fpath.is_file():
                    continue
                resolved = fpath.resolve()
                if not resolved.is_relative_to(root.resolve()):
                    continue
            except OSError:
                continue

            inv.files_discovered += 1

            if is_secret_file(fname):
                inv._bump("secret_guarded")
                continue

            suffix = fpath.suffix.lower()
            language = LANGUAGE_BY_EXT.get(suffix)
            # ".env.example".suffix is ".example" (pathlib splits on the last
            # dot regardless of the leading dotfile convention), so it needs
            # an explicit name check rather than a suffix lookup.
            is_config_doc = (
                suffix in _CONFIG_DOC_EXTS
                or _is_special_config_name(fname)
                or fname in ENV_EXAMPLE_NAMES
            )

            if suffix in SKIP_SUFFIXES:
                inv._bump("binary_or_lockfile")
                continue

            if language:
                inv.source_files_discovered += 1
                inv.languages[language] = inv.languages.get(language, 0) + 1

            if not language and not is_config_doc:
                inv._bump("unrecognised_extension")
                continue

            if _is_generated_name(fname):
                inv._bump("generated")
                continue

            try:
                rel_posix = fpath.relative_to(root).as_posix()
            except ValueError:
                continue

            if is_binary(fpath):
                inv._bump("binary")
                continue

            if language and _is_minified(fpath):
                inv._bump("minified")
                continue

            if (
                fname not in ENV_EXAMPLE_NAMES
                and language
                and _looks_generated_header(fpath)
            ):
                inv._bump("generated")
                continue

            lines, size = _count_lines_and_bytes(fpath)
            if size > ARCH_MAX_FILE_BYTES:
                inv._bump("oversize_file")
                if language:
                    # Still counted toward discovery/language stats above,
                    # but not added to the parseable pool.
                    continue

            record = FileRecord(
                rel_path=rel_posix,
                abs_path=fpath,
                ext=suffix,
                size=size,
                lines=lines,
                language=language,
                is_config_doc=is_config_doc,
                is_test=_is_test_path(rel_posix),
                is_generated=False,
            )
            inv.files.append(record)
            if language:
                inv.source_bytes += size
                inv.source_lines += lines

        else:
            continue
        break

    inv.files.sort(key=lambda f: f.rel_path)
    return inv


def choose_tier(inv: Inventory) -> tuple[int, str | None]:
    """(tier, limit_exceeded) — tier is an entry decision; a Tier-1 run can
    still finish as status="partial" if a runtime/graph bound is hit later."""
    if inv.truncated_walk:
        return 3, "ARCH_MAX_DISCOVERED_FILES"
    if inv.source_files_supported == 0 and inv.source_files_discovered == 0:
        return 3, "no_source_files_found"
    if inv.source_bytes > ARCH_MAX_SOURCE_BYTES:
        return 2, "ARCH_MAX_SOURCE_BYTES"
    if inv.source_lines > ARCH_MAX_SOURCE_LINES:
        return 2, "ARCH_MAX_SOURCE_LINES"
    if inv.source_files_supported > ARCH_MAX_PARSED_FILES:
        return 2, "ARCH_MAX_PARSED_FILES"
    if inv.source_files_supported == 0:
        # Only unsupported languages present — still a real inventory, but no
        # component graph can be built from imports.
        return 2, "no_supported_source_files"
    return 1, None


def priority_key(f: FileRecord) -> tuple[int, int, str]:
    """Sort key for choosing which files to parse under a budget: shallower
    paths first, smaller files as a tiebreak, then path for determinism."""
    depth = f.rel_path.count("/")
    return (depth, f.size, f.rel_path)
